# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eae1f162a18857f3c67c508f41aa9af1243524a028d2a5d4d8e8335a16eb72c3473ee9074cc4864f4ea13d33b1bcbc87ec99047c12cb3a5f65feec0669015001

test:
  secret_key_base: f8c759130ca2314f265aeca14e48ea439ed476c735050fc06c481ff8a979dff82d02bb4177ac1622fe949427a218ca3194cd4d239c4a59dfb171760c25a10ad4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
